name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:


# GNU/Linux: VUnit Action (uses Docker image ghdl/vunit:llvm)

  lin-vunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: VUnit/vunit_action@v0.1.0


# GNU/Linux: Custom Docker image

  lin-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t vunit/tdd - < .github/Dockerfile
    - run: docker run --rm -v $(pwd):/src -w /src -e CI vunit/tdd python3 -m pytest -v -s -ra test.py --color=yes


# GNU/Linux: GHDL Action + custom Python packages

  lin-setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --progress-bar off pytest vunit_hdl
        python -m pytest -v -s -ra test.py --color=yes


# Windows: MSYS2 Action + GHDL Action + custom Python packages

  win-setup:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-python-pip
    - uses: actions/checkout@v2
    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm
    - run: |
        python -m pip install --progress-bar off pytest vunit_hdl
        python -m pytest -v -s -ra test.py --color=yes


# Windows: standalone GHDL zipfile/tarball + custom Python packages

  win-stable:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - env:
        WINDOWS_RELEASE: 0.37-mingw64-llvm
      shell: bash
      run: |
        curl -fsSL -o ghdl.zip https://github.com/ghdl/ghdl/releases/download/v0.37/ghdl-${WINDOWS_RELEASE}.zip
        7z x ghdl.zip "-o../ghdl-tmp" -y
        mv ../ghdl-tmp/GHDL/${WINDOWS_RELEASE}/ ../ghdl
        rm -rf ../ghdl-tmp ghdl.zip
        export PATH=$PATH:$(pwd)/../ghdl/bin
        python -m pip install --progress-bar off pytest vunit_hdl
        python -m pytest -v -s -ra test.py --color=yes
